/* eslint-disable @next/next/no-img-element */
import Head from 'next/head'
import Link from 'next/link'
import Navbar from '@/components/navbar'

import { Inter } from '@next/font/google'
import Gallery from '@/components/gallery'
import Projects from '@/components/projects'
import Team from '@/components/team'
import Footer from '@/components/footer'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Home | Mavericks Club - SLIET</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" type="image/x-icon" href="/mavericks-logo.png"/>
      </Head>

      <Navbar />

      {/* ########## Header ###################  */}

      <section className="text-gray-600 body-font">
        <div className="container mx-auto flex px-5 py-24 md:flex-row flex-col items-center">
          <div className="lg:flex-grow md:w-1/2 lg:pr-24 md:pr-16 flex flex-col md:items-start md:text-left mb-16 md:mb-0 items-center text-center">
            <h1 className="title-font sm:text-6xl text-6xl mb-4 font-medium text-gray-900">Mavericks
            </h1>
            <h1 className="title-font sm:text-4xl text-4xl mb-4 font-medium text-gray-900">Born to be Different
            </h1>
            <p className="mb-8 leading-relaxed">It provides an ideal platform for student of Mechanical, Mechatronics, Electronics, Computers, Electrical engineering background to hone their skills and showcase their talent in many interdisciplinary activities</p>
            <div className="flex justify-center">
              <button className="inline-flex text-white bg-orange-500 border-0 py-2 px-6 focus:outline-none hover:bg-orange-700 rounded text-lg">Explore Now</button>
              <button className="ml-4 inline-flex text-gray-700 bg-gray-100 border-0 py-2 px-6 focus:outline-none hover:bg-gray-200 rounded text-lg">Query?</button>
            </div>
          </div>
          <div className="lg:max-w-lg lg:w-full md:w-1/2 w-5/6">
            <img className="object-cover object-center rounded-xl" alt="hero" src="/images/line-follwing.jpg"/>
          </div>
        </div>
      </section>


      {/* ################## Gallery ##########################  */}

      <Gallery />


      <Projects />

      <Team />

      <Footer />

    </>
  )
}
